# Generated by Django 5.0 on 2023-12-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.PositiveIntegerField()),
                ('First_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('fields_of_study', models.CharField(max_length=100)),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
